authors:
    madeline:
        name: Madeline Montigny
        description: Ingénieure pédagogique
        avatar: https://phoneimpact.inria.fr/blog/img/MadelineMontigny.jpg
        url: https://www.linkedin.com/in/madelinemontigny/
    sherazade:
        name: Sherazade Djeballah
        description: Ingénieure pédagogique
        avatar: https://phoneimpact.inria.fr/blog/img/Sherazade.jpeg
        url: https://www.linkedin.com/in/sherazade-djeballah-6a8759233/
    sabah:
        name: Sabah Khalfa
        description: Ingénieure pédagogique
        avatar: https://phoneimpact.inria.fr/blog/img/SabahKhalfa.jpeg
        url: https://www.linkedin.com/in/sabah-khalfa-ab24749/
    pauline:
        name: Pauline Robic
        description: Cheffe de projet Numérique et Ecologie
        avatar: https://phoneimpact.inria.fr/blog/img/PaulineRobic.jpg
        url: https://www.linkedin.com/in/pauline-robic-b6b4a414b/
    AssociationInformatiqueParticipative:
        name: Association pour l’Informatique participative
        description: Médiation, reconditionnement et promotion des logiciels libre sont les 3 activités de l'association
        avatar: https://phoneimpact.inria.fr/blog/img/InformatiqueParticipative.jpg
        url: https://www.linkedin.com/company/informatique-participative/
    camille:
        name: Camille Picard
        description: Cheffe de projet en médiation scientifique chez Inria
        avatar: https://phoneimpact.inria.fr/blog/img/CamillePicard.jpg
        url: https://www.linkedin.com/in/cam-picard/
    DRASI:
        name: Le cercle numérique responsable
        description: Direction régionale académique des systèmes d'information de Bretagne
        avatar: https://phoneimpact.inria.fr/blog/img/drasi.jpg
        url:
    victorien:
        name: Victorien Elvinger
        description: Ingénieur de Recherche au sein de l'équipe MAGELLAN
        avatar: https://phoneimpact.inria.fr/blog/img/victorien.jpg
        url: https://fr.linkedin.com/in/victorien-elvinger/fr
    benjamin:
        name: Benjamin Ninassi
        description: Adjoint au directeur du programme Numérique et Environnement d’Inria
        avatar: https://phoneimpact.inria.fr/blog/img/benjamin.jpg
        url: https://www.linkedin.com/in/bninassi/
